USE test;

DROP TABLE IF EXISTS books;

CREATE TABLE `books` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `description` varchar(255) NOT NULL,
  `author` varchar(100) NOT NULL,
  `isbn` varchar(20) NOT NULL,
  `printYear` int(11) NOT NULL,
  `readAlready` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);

INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Властелин Колец. Том 1. Братство кольца', 'Вечная тема борьбы Добра и Зла, большой подвиг маленького героя и, самое главное, - тот фантастический и вместе с тем уди­вительно реальный мир, в котором хочется остаться навсегда.', 'Толкин Джон Рональд Руэл', '9785170818020', '2014');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Hobbit', 'Bilbo Baggins enjoys a quiet and contented life, with no desire to travel far from the comforts of home; then one day the wizard Gandalf and a band of dwarves arrive unexpectedly and enlist his services as a burglar on a dangerous expedition.', 'J. R. R. Tolkien', '9780261103283', '2007');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Don Quijote de la Mancha', 'La historia de don Quijote es la imagen mas completa у mas rica, porque en el la estan representadas todas las historias у todos los personajes de su tiempo.', 'Miguel de Cervantes', '8437622093', '2006');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Harry Potter and the Goblet of Fire', 'The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter – but that doesn’t stop Harry dreaming that he will win the competition.', 'J.K. Rowling', '9781408855928', '2014');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Le Tour du monde en quatre-vingts jours', 'Le roman raconte la course autour du monde d\'un gentleman anglais, Phileas Fogg, qui a fait le pari d\'y parvenir en quatre-vingts jours.', 'Jules Gabriel Verne', '9782253012696', '1976');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Vingt mille lieues sous les mers', 'Le professeur Aronnax, son domestique Conseil et le harponneur Ned Land, qui cherchaient à capturer un fantastique monstre marin, se retrouvent prisonniers du capitaine Némo, à bord de son sous-marin le Nautilus.', 'Jules Gabriel Verne', '2253006327', '2001');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('L\'Île mystérieuse', 'Au cours de la guerre de Sécession, cinq Nordistes : l\'ingénieur Cyrus Smith et son chien Top, le reporter Gédéon Spilett, le Noir Nab, le marin Pencroff et le jeune Harbert, prisonniers des troupes séparatistes, se sont enfuis en ballon.', 'Jules Gabriel Verne', '2253160865', '2002');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Voyage au centre de la Terre', 'Un fou de savant (il en produira par dizaines, de ces illuminés, tous plus extravagants les uns que les autres) descend en compagnie d\'un adolescent candide et d\'un guide muet.', 'Jules Gabriel Verne', '2253012548', '1972');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Les Enfants du capitaine Grant', 'Sur la foi d\'un message trouvé dans une bouteille et à demi rongé par l\'eau de mer, le magnifique yacht anglais, le Duncan, part à la recherche du capitaine Grant naufragé.', 'Jules Gabriel Verne', '2253160881', '2005');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Ревизор', 'Одна из лучших русских комедий. Н.В. Гоголь заставил современников смеяться над тем, к чему они привыкли и что перестали замечать.', 'Гоголь Николай Васильевич', '9785699693931', '2017');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Отцы и дети', 'В романе отразилась идеологическая борьба двух поколений, являвшаяся одной из главных особенностей общественной жизни 60-х годов XIX века.', 'Тургенев Иван Сергеевич', '5080039884', '2017');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Герой нашего времени', 'Имя Печорина давно стало нарицательным. Молодой офицер, прибыв на Кавказ и скучая в глуши, попадает в полные драматизма истории, покоряет женские сердца, навлекает на себя гнев горцев, оказывается в компании контрабандистов.', 'Лермонтов Михаил Юрьевич', '9785444412442', '2017');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Евгений Онегин', 'Роман в стихах русского поэта Александра Сергеевича Пушкина, написанный в 1823—1831 годах, одно из самых значительных произведений русской словесности.', 'Пушкин Александр Сергеевич', '9785910455706', '2014');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Преступление и наказание', 'В основу сюжета легло преступление студента Родиона Раскольникова, убившего ради спасения близких старуху-процентщицу. Криминальная история стала для автора поводом для размышлений...', 'Достоевский Федор Михайлович', '9785001120322', '2017');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Горе от ума', 'Комедия «Горе от ума» — сатира на аристократическое московское общество первой половины XIX века — одна из вершин русской драматургии и поэзии.', 'Грибоедов Александр Сергеевич', '9785001080831', '2017');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Romeo and Juliet', 'When Romeo first lays eyes on the bewitching Juliet, it\'s love at first sight. But though their love runs true and deep, it is also completely forbidden. With family determined to keep them apart, will Romeo and Juliet find a way to be together?', 'William Shakespeare', '9780061965494', '2009');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Los de abajo', 'Se trata de una historia descarnada, concebida con la sinceridad y la valentía de un hombre que nunca cedió a la tentación de adornar artificiosamente o falsear los acontecimientos.', 'Mariano Azuela', '9789681681999', '2008');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('El coronel no tiene quien le escriba', 'Un viejo coronel retirado espera que la patria le compense por los servicios prestados. Pero la patria permanece muda...', 'Gabriel García Márquez', '9788439729235', '20014');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('El otoño del patriarca', 'El otoño del patriarca deja asomar en su trasfondo el acontecimiento más importante de la historia española de aquellos años, la muerte del general Franco.', 'Gabriel García Márquez', '9788439729839', '2015');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('Cien años de soledad', 'Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.', 'Gabriel García Márquez', '9788439728368', '2014');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Spy: A Tale of the Neutral Ground', 'A historical adventure reminiscent of Sir Walter Scott’s Waverley romances, Cooper’s novel centers on Harvey Birch, a common man suspected of being a spy for the British.', 'James Fenimore Cooper', '9781414273495', '2004');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Pioneers: or The Sources of the Susquehanna', 'The Pioneers is a rich chronicle of early frontier life filled with action, adventure, romance, and history. It is also the work that established James Fenimore Cooper as the first great American novelist.', 'James Fenimore Cooper', '9780873954235', '1980');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Last of the Mohicans', 'Deep in the forests of upper New York State, the brave woodsman Hawkeye (Natty Bumppo) and his loyal Mohican friends Chingachgook and Uncas become embroiled in the bloody battles of the French and Indian War.', 'James Fenimore Cooper', '9780553213294', '1982');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Deerslayer: or The First Warpath', 'Danger has invaded the vast forests of upper New York State as Deerslayer and his loyal Mohican friend Chingachgook attempt the daring rescue of an Indian maiden imprisoned in a Huron camp.', 'James Fenimore Cooper', '9780553210859', '1991');
INSERT INTO books (title, description, author, isbn, printYear) VALUES ('The Pathfinder, or The Inland Sea', 'The novel revives Natty Bumppo and casts him, with his friend, the Mohican chief Chingachgook, among Tuscarora and Iroquois Indians, and into conflicts over land and love.', 'James Fenimore Cooper', '9780192829566', '1992');
